services:
  mongodb:
    image: mongo:7-jammy
    
    container_name: mongodb
    
    ports:
      - "27007:27017"
    
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

    volumes:
      - mongodata:/data/db
    
    networks:
      - backend

    restart: always

  pgvector:
    image: pgvector/pgvector:0.8.0-pg17
    
    container_name: pgvector
    
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    
    ports:
      - "5432:5432"
    
    volumes:
      - pgdata:/var/lib/postgresql/data

    restart: always
    
    networks:
      - backend
      
networks:
  backend:

volumes:
  mongodata:
  pgdata:

